- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.23
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "exampleuser"
        password: "us3rp@ssw0rd"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
  tasks:
    get_url:
<<<<<<< HEAD
        url: https://s3gol.s3.amazonaws.com/gameoflife-web/target/gameoflife.war
        dest: /tomcat/webapps/gameoflife  
=======
      url: https://s3gol.s3.amazonaws.com/gameoflife-web/target/gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife  
>>>>>>> 47318f5b9bd5ba70017fbd8052347a9321ef5afd
